CREATE TABLE learning_levels (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(256) NOT NULL UNIQUE,
	description TEXT);
CREATE TABLE phrase_types (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(256) NOT NULL UNIQUE);
CREATE TABLE tags (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(256) NOT NULL UNIQUE,
	description TEXT);
CREATE TABLE phrases (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	text TEXT NOT NULL UNIQUE,
	meaning TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	phrase_type_id INTEGER REFERENCES phrase_types(id),
	learning_level_id INTEGER REFERENCES learning_levels(id));
CREATE TABLE phrases_tags_linking (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	tag_id INTEGER REFERENCES tags(id),
	phrase_id INTEGER REFERENCES phrases(id));